name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deployment Webhook
        run: |
          curl -sS -L -X GET "https://sbdigital.biz.id/api/deploy/${{ secrets.DEPLOY_TOKEN }}" -H "Accept: application/json" -H "User-Agent: GitHubActions/1.0"